# -*- coding: utf-8 -*-
# Mapa de alt text especifico por foto, escrito a partir de inspeccion visual real.
# key: ruta relativa desde la raiz del repo (igual a como aparece en fotos_de()).
ALT = {}

def add(carpeta, archivo, texto):
    ALT[f'img/trabajos/{carpeta}/{archivo}'] = texto

# ---------------------------------------------------------------- REJAS
add('rejas', '10.webp', 'Reja de ventana blanca con barrotes en diseño de rombos cruzados')
add('rejas', '11.webp', 'Puerta doble de hierro con vidrio repartido, pintada de blanco')
add('rejas', '12.webp', 'Portón de reja negro con florones circulares, en proceso de instalación')
add('rejas', '2.webp', 'Portón corredizo negro de paneles macizos con reja superior')
add('rejas', '3.webp', 'Portón de garaje corredizo blanco con material desplegado y puerta peatonal')
add('rejas', '4.webp', 'Portón peatonal negro con malla romboidal para patio trasero')
add('rejas', '5.webp', 'Portón peatonal doble hoja con florones ornamentales y puntas de lanza')
add('rejas', '6.webp', 'Portón corredizo con material desplegado y puntas antivandálicas')
add('rejas', '7.webp', 'Portón y puerta combinados con material desplegado y puntas de seguridad')
add('rejas', '8.webp', 'Reja de puerta de entrada con barrotes torsionados, sobre puerta de madera')
add('rejas', '9.webp', 'Portón corredizo negro con barrotes rectos y torsionados sobre pared de ladrillo')
add('rejas', 'reja1.webp', 'Reja perimetral con puntas de lanza y barrotes torsionados sobre muro de piedra')
add('barandas', '1.webp', 'Baranda de escalera interior negra, diseño minimalista con panel enrejado')
add('barandas', '9f8e91dc-809f-4275-bc55-9eddec9b0859.webp', 'Baranda de escalera negra minimalista con pasamanos curvado')

# ---------------------------------------------------------------- MUEBLES
add('muebles', '1.webp', 'Mesas ratonas anidadas de hierro negro con tapa de madera')
add('muebles', '10.webp', 'Alacena de cocina a medida en melamina símil madera, con estantes y microondas integrado')
add('muebles', '11.webp', 'Mueble bajo de hierro negro con estante de material desplegado y tapa de madera')
add('muebles', '12.webp', 'Mesada rodante de hierro negro con tapa de madera y estante de material desplegado, junto a pileta')
add('muebles', '13.webp', 'Barra de bar exterior de hierro negro con tapa de madera y banquetas, junto a piscina')
add('muebles', '14.webp', 'Escritorio flotante de pared en hierro negro y madera, con silla en Z')
add('muebles', '15.webp', 'Silla en forma de Z, estructura de hierro negro con asiento y respaldo de madera')
add('muebles', '16.webp', 'Botellero de hierro de gran capacidad para bodega')
add('muebles', '17.webp', 'Escritorio de hierro y madera maciza con puerta corrediza tipo granero y cajones')
add('muebles', '18.webp', 'Placard a medida en melamina símil madera con cajonera y estantes superiores')
add('muebles', '19.webp', 'Placard de chapa blanco con estantes internos')
add('muebles', '2.webp', 'Biblioteca alta y angosta de hierro negro con cinco estantes')
add('muebles', '20.webp', 'Mesas ratonas redondas anidadas, tapa de madera y base de hierro negro, junto a piscina')
add('muebles', '21.webp', 'Mesa de trabajo de hierro con tapa de madera y estante de material desplegado, con carrito auxiliar')
add('muebles', '22.webp', 'Banqueta alta con patas de hierro tipo horquilla y asiento de tablas de madera')
add('muebles', '23.webp', 'Juego de sillones y banco de patio en tubo de hierro rojo con listones de madera, junto a jacuzzi')
add('muebles', '24.webp', 'Sofá de hierro con estructura curva y cojines, para galería')
add('muebles', '25.webp', 'Mesa auxiliar rectangular de hierro negro con dos estantes de material desplegado')
add('muebles', '26.webp', 'Mesa de luz de hierro negro con tapa de madera y estante inferior')
add('muebles', '27.webp', 'Mesa alta con tapa de hierro negro y agarradera integrada')
add('muebles', '28.webp', 'Mesada de cocina a medida en melamina símil madera con bacha de acero inoxidable')
add('muebles', '29.webp', 'Escritorio en L con biblioteca lateral, hierro negro y madera')
add('muebles', '4.webp', 'Escritorio con biblioteca lateral integrada, hierro negro y madera oscura')
add('muebles', '5.webp', 'Banqueta alta de madera de pino sin terminar')
add('muebles', '6.webp', 'Mesa alta de madera de pino con banquetas y estantes de listones, sobre ruedas')
add('muebles', '7.webp', 'Carrito de madera de pino con dos estantes de listones y ruedas')
add('muebles', '8.webp', 'Mesas ratonas de hierro negro con patas geométricas, junto a piscina')
add('muebles', '9.webp', 'Mesa larga de comedor en madera maciza oscura, estilo rústico, con seis sillas')
add('muebles', 'barra1.webp', 'Isla de cocina con tapa de madera y estructura de hierro con material desplegado')
add('muebles', 'mesa1.webp', 'Mesa de comedor grande, tapa de madera maciza y base de hierro negro, bajo galería')

# ---------------------------------------------------------------- CERRAMIENTOS
add('cerramientos', '23.webp', 'Puerta doble de chapa negra con rejilla de ventilación, cerramiento de depósito')
add('cerramientos', '4b688aa9-1384-47b1-9d69-7cb66ed5a314.webp', 'Cerramiento de esquina con paneles de hierro entrelazado tipo cesta, en negro')
add('cerramientos', '6acee17d-f2c9-4dac-8f8c-7a10f2e1669d.webp', 'Puerta corrediza con vidrio esmerilado y marco geométrico, en blanco')
add('cerramientos', '981fb062-81b3-44ab-b766-49ab79fbe376.webp', 'Puertas de hierro con paneles entrelazados tipo cesta, cerramiento de galería')
add('cerramientos', 'a14d55d6-7d6b-4e26-8287-6dd7fbbf3144.webp', 'Horno de barro con puertas de hierro negro y termómetro, sobre parrilla de ladrillo visto')
add('cerramientos', 'bcd29f87-1087-48df-94fd-2558e32bcf3b.webp', 'Portón de cerramiento con material desplegado, bajo techo con detalles de hierro forjado')
add('cerramientos', 'c9785a16-b294-4e33-8f5f-777c8f3924ff.webp', 'Puerta a medida bajo escalera, gris, con estantes internos triangulares')
add('cerramientos', 'cerramiento_bobadilla.webp', 'Puerta de quincho con cartel decorativo y diseño en X, negro con detalle plateado')
add('cerramientos', 'f3997592-82a3-4150-945c-0d0af816217c.webp', 'Portón doble de chapa gris con paneles rectangulares, para depósito exterior')
add('cerramientos', 'fab79dd3-7157-4c9b-a872-9c68493cda96.webp', 'Cerramiento de asador con puertas dobles negras y alacenas, sobre pared de ladrillo visto')
add('cerramientos', 'quincho_napoles.webp', 'Puerta de quincho con cartel personalizado, en gris oscuro')

# ---------------------------------------------------------------- TECHOS
add('techos', '7.webp', 'Techo de cochera con estructura de hierro y policarbonato translúcido')
add('techos', '8.webp', 'Pérgola con techo de caña sobre estructura de hierro negro')
add('techos', '9.webp', 'Techo con media sombra sobre estructura de hierro, vista desde abajo')
add('techos', 'techo1.webp', 'Techo de cochera en chapa sobre estructura de hierro gris')
add('techos', 'techo2.webp', 'Galería con techo de chapa translúcida y estructura de hierro azul, sobre patio con asador')
add('techos', 'techo3.webp', 'Galería de chapa translúcida con estructura de hierro negro, sobre patio con asador')
add('techos', 'techo4.webp', 'Techo de policarbonato con cenefa de hierro forjado decorativa')
add('techos', 'techo5.webp', 'Techo de galería en policarbonato sobre estructura de hierro, en jardín')
add('techos', 'techo6.webp', 'Marquesina de madera sobre local comercial')
add('techos', 'techo_vero.webp', 'Techo de galería con estructura de hierro azul, al atardecer')

# ---------------------------------------------------------------- ESPEJOS
add('espejos', '1.webp', 'Espejo redondo con marco de hierro negro, sobre consola de entrada')
add('espejos', '10.webp', 'Espejo rectangular con marco de hierro negro dividido en paneles')
add('espejos', '11.webp', 'Espejo rectangular grande con marco plateado dividido en paneles, sobre mesa de comedor')
add('espejos', '12.webp', 'Espejo rectangular con marco plateado dividido en paneles, sobre aparador')
add('espejos', '13.webp', 'Espejo redondo con marco de hierro negro tipo rueda, con divisiones radiales')
add('espejos', '14.webp', 'Espejo rectangular con marco dorado dividido en paneles, sobre mesa de comedor')
add('espejos', '15.webp', 'Detalle de espejo con marco de madera, en galería exterior')
add('espejos', '16.webp', 'Espejo de cuerpo entero tipo arco con marco de hierro negro y divisiones')
add('espejos', '2.webp', 'Espejo redondo de baño con marco de hierro, sobre bacha con azulejos patchwork')
add('espejos', '3.webp', 'Tres espejos ovalados de tamaños distintos con marco de hierro negro, sobre bacha de baño')
add('espejos', '4.webp', 'Espejo de cuerpo entero con marco de hierro negro fino, apoyado en el piso')
add('espejos', '5.webp', 'Espejo tipo arco con marco de hierro negro y divisiones, sobre consola de mármol')
add('espejos', '6.webp', 'Espejo de cuerpo entero con marco de hierro negro en diseño geométrico asimétrico')
add('espejos', '7.webp', 'Espejo con marco de hierro negro y esquinas redondeadas')
add('espejos', '8.webp', 'Espejo de cuerpo entero con marco de hierro negro dividido en paneles geométricos')
add('espejos', '9.webp', 'Espejo de cuerpo entero con marco de hierro cobrizo en diseño geométrico')
add('espejos', 'fd126e2b-3187-4de3-8590-5b2c13799c99.jpg2.webp', 'Espejo retroiluminado con forma orgánica tipo ameba y luz LED perimetral')

# ---------------------------------------------------------------- DECKS
add('decks', 'deck.webp', 'Deck de madera perimetral de pileta cuadrada, en patio con macetas')
add('decks', 'foto_deck_1.webp', 'Deck de madera junto a pileta ovalada, con pared de ladrillo visto')
add('decks', 'foto_deck_2.webp', 'Escalera y entrepiso de madera a medida en un living con paredes de ladrillo visto')
add('decks', 'foto_deck_3.webp', 'Deck con escalones de madera bajando hacia pileta con iluminación LED, de noche')
add('decks', 'foto_deck_4.webp', 'Deck de madera perimetral de pileta rectangular')
add('decks', 'foto_deck_5.webp', 'Deck elevado con escalones de madera, pileta cuadrada bajo galería')
add('decks', 'foto_deck_6.webp', 'Deck perimetral amplio con escalones de madera junto a pileta ovalada')
add('decks', 'foto_deck_7.webp', 'Deck de madera perimetral de pileta cuadrada, en patio con macetas')
add('decks', 'foto_deck_8.webp', 'Piso de madera con estructura de hierro y paneles de cerramiento, en un local comercial')

# ---------------------------------------------------------------- ELEMENTOS DE COCINA
add('elemCocina', '1.webp', 'Parrilla circular a caballete con ruedas y chimenea central')
add('elemCocina', '2.webp', 'Parrilla circular con sistema de asador giratorio sobre ruedas')
add('elemCocina', '3.webp', 'Soportes de hierro con varillas onduladas para asador, sobre pared de ladrillo')
add('elemCocina', '4.webp', 'Parrilla de dos niveles, con varillas y sector de material desplegado')
add('elemCocina', '5.webp', 'Base de hierro tipo caballete con varillas para parrilla')
add('elemCocina', '6.webp', 'Parrilla rectangular con varillas y sector de material desplegado')
add('elemCocina', '76912718-5598-4243-b3a6-183385c2c7d7.webp', 'Parrilla rectangular con varillas y sector de material desplegado')
add('elemCocina', 'mini_bar.webp', 'Mini bar de hierro negro con estantes, para botellas y copas')

# ---------------------------------------------------------- FOTOS 2026 (nuevas)
add('rejas', 'reja-2026-01.webp', 'Reja de ventana con barrotes torsionados y puntas de lanza')
add('rejas', 'reja-2026-02.webp', 'Cerco perimetral con barrotes torsionados y puntas de lanza, sobre muro de piedra')
add('rejas', 'reja-2026-03.webp', 'Detalle de cerco perimetral con barrotes torsionados y puntas de lanza')
add('rejas', 'reja-2026-04.webp', 'Portón peatonal con barrotes torsionados y puntas de lanza, en escalera de entrada')
add('rejas', 'reja-2026-05.webp', 'Portón peatonal con barrotes torsionados, junto a portero eléctrico')
add('rejas', 'reja-2026-06.webp', 'Cerco perimetral completo con barrotes torsionados y puntas de lanza sobre muro de piedra')
add('muebles', 'mueble-2026-01.webp', 'Mesa alta con tapa de hierro negro y agarradera integrada')
add('muebles', 'mueble-2026-02.webp', 'Mesa ratona rectangular con tapa de madera veteada y base de hierro negro')
add('muebles', 'mueble-2026-03.webp', 'Mesa de comedor con tapa de madera maciza veteada y base de hierro negro')
add('muebles', 'mueble-2026-04.webp', 'Mesa ratona con tapa de madera maciza y base de hierro negro')
add('muebles', 'mueble-2026-05.webp', 'Mesa de comedor rectangular con tapa de madera veteada y base de hierro negro')
add('muebles', 'mueble-2026-06.webp', 'Detalle de la veta de una mesa de madera maciza con base de hierro negro')
add('elemCocina', 'cocina-2026-01.webp', 'Isla de cocina exterior con parrilla integrada, mesada de madera y banquetas')
add('elemCocina', 'cocina-2026-02.webp', 'Parrilla de asador con varillas y accesorios, dentro de un hogar de ladrillo')
add('elemCocina', 'cocina-2026-03.webp', 'Parrilla rectangular con varillas y sector de material desplegado')
add('elemCocina', 'cocina-2026-04.webp', 'Carrito con plancha de hierro fundido y agarraderas')
add('elemCocina', 'cocina-2026-05.webp', 'Parrilla de dos niveles con varillas y sector de material desplegado')
add('elemCocina', 'cocina-2026-06.webp', 'Plancha de hierro fundido con agarraderas, sobre estructura de patas negras')
add('elemCocina', 'cocina-2026-07.webp', 'Base de hierro tipo caballete con varillas para parrilla')
add('decks', 'deck-2026-01.webp', 'Deck de madera perimetral de pileta cuadrada, en patio con macetas')
add('cerramientos', 'cerramiento-2026-01.webp', 'Puerta corrediza tipo granero, gris, sobre hogar de ladrillo visto')

# ---------------------------------------------------------------- OTROS TRABAJOS
add('otros_trabajos', '1.webp', 'Cesto de material desplegado sobre poste de hierro, en la vía pública')
add('otros_trabajos', '2.webp', 'Lámpara colgante tipo esfera armilar, cintas de hierro entrelazadas')
add('otros_trabajos', '3.webp', 'Refacción de fachada y cartelería en madera para el country Campo de Vuelo')
add('otros_trabajos', '4.webp', 'Detalle de lámpara colgante tipo esfera armilar de hierro')
add('otros_trabajos', '5.webp', 'Toallero escalera de hierro negro para baño')
add('otros_trabajos', '6.webp', 'Cesto de material desplegado con terminación oxidato, sobre poste de hierro')
